### ISSUE TITLE
Allow white listing of gene IDs which should always appear in output

### ISSUE THREAD

**Issue by ellendejong** [STAR-Fusion/STAR-Fusion#118]
Hi Brian,

I have two semi unrelated questions. Currently described in one issue, but I am happy to split them into two issues if required.

**_First: is it possible to not filter the red herring events and flag them instead?_** 
We want to have a look into some events that end up in the filtered output and want to treat them with care. Therefore a flag would help us a lot. I know it is possible to provide the parameter _--no_annotation_filter_, but I was wondering whether you still see a flag showing that the event would originally appear in the filtered out events. 

_**Secondly: Is it possible to use a (white) list containing certain genes involved in an event that should always be reported in final output?**_ We are running STAR-Fusion on RNA-Seq in a diagnostic setting and found out that sometimes an event related to a specific disease has low FFPM value. With our default FFPM threshold, it is removed from the final output. As part of the solution we are thinking about running STAR-Fusion with FFPM always zero and than filter out afterwards those with FFPM lower than threshold that do not appear in the white list.
Maybe this is also related to question 1. If it would be possible to use a list of gene IDs, and never filter those out and have extra columns for annotation (red herring flag, flag presence in white lists etc.), would be great. Is this already possible?

Some notes:

- We are currently using following software versions. We hope to switch soon to the newest released version of both.
STAR-2.6.1b
STAR-Fusion-1.4.0
- We use _star-fusion.fusion_predictions.abridged.coding_effect.tsv_ as our final output.

Thanks in advance.

Ellen.

**Comment by brianjohnhaas** [comment]
Hi Ellen,

In the latest version of STAR-Fusion, there should be an intermediate
output file called:


star-fusion.preliminary/star-fusion.fusion_candidates.preliminary.wSpliceInfo.wAnnot

that contains all preliminary fusion predictions including fusion
annotations and FFPM values, and this is the file that would later be
filtered for predictions based on red-herring and FFPM filters.   I'm
thinking you could just use this file to see if you capture anything that
would be on your 'whitelist'.

If there are real cancer-related fusions that are showing up in samples and
not being reported in the final list due to the FFPM filter, then that
would suggest a problem with our FFPM filtering threshold.  I know there
are cases where commercial fusion spike-ins aren't picked up in next gen
sequencing assays w/ high FFPMs, and that's just because they're spiked
into background RNA at very low concentrations - low enough that you can
use them for PCR validation, but not for next-gen sequencing unless first
PCR-amplified.

If you need something specially implemented in star-fusion, just let me
know and I can add it to the roadmap for a future release.

best,

~brian


On Tue, Feb 19, 2019 at 7:32 AM EllenDeJong <notifications@github.com>
wrote:
>
> Hi Brian,
>
> I have two semi unrelated questions. Currently described in one issue,
but I am happy to split them into two issues if required.
>
> First: is it possible to not filter the red herring events and flag them
instead?
> We want to have a look into some events that end up in the filtered
output and want to treat them with care. Therefore a flag would help us a
lot. I know it is possible to provide the parameter --no_annotation_filter,
but I was wondering whether you still see a flag showing that the event
would originally appear in the filtered out events.
>
> Secondly: Is it possible to use a (white) list containing certain genes
involved in an event that should always be reported in final output? We are
running STAR-Fusion on RNA-Seq in a diagnostic setting and found out that
sometimes an event related to a specific disease has low FFPM value. With
our default FFPM threshold, it is removed from the final output. As part of
the solution we are thinking about running STAR-Fusion with FFPM always
zero and than filter out afterwards those with FFPM lower than threshold
that do not appear in the white list.
> Maybe this is also related to question 1. If it would be possible to use
a list of gene IDs, and never filter those out and have extra columns for
annotation (red herring flag, flag presence in white lists etc.), would be
great. Is this already possible?
>
> Some notes:
>
> We are currently using following software versions. We hope to switch
soon to the newest released version of both.
> STAR-2.6.1b
> STAR-Fusion-1.4.0
> We use star-fusion.fusion_predictions.abridged.coding_effect.tsv as our
final output.
>
> Thanks in advance.
>
> Ellen.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by ellendejong** [comment]
Thanks!

**Comment by ellendejong** [comment]
Sorry for asking help again. I looked at star-fusion.preliminary/star-fusion.fusion_candidates.preliminary.wSpliceInfo.wAnnot, which contains most information that we need. However, we would like to have the coding effect annotation columns as well. I found out that this is added via fusionInspector. Since there are so many output-files, I am kind of lost. Is it possible to run fusionInspector again on  star-fusion.preliminary/star-fusion.fusion_candidates.preliminary.wSpliceInfo.wAnnot? Or is it already provided in one of the output files?

**Comment by brianjohnhaas** [comment]
It should be possible to run the coding effect analysis on that preliminary
file separately but it'll generate a large output file where most of the
results are going to be unhelpful.  Perhaps you want to do a supervised
search first based on your whitelist and then follow those up with
fusioninspector... ?

-via googleFi
