### ISSUE TITLE
AKAP9-BRAF fusion was missed because of blast filtering

### ISSUE THREAD

**Issue by helloeoh001** [STAR-Fusion/STAR-Fusion#168]
Hello,

I am going to raise another issue with blast-filtering which could result in false negative fusion genes.
One of my clinical sample harbored 'AKAP9-BRAF' fusion which is well-known in tyroid cancer.
The gene-fusion was missed when anayzing with STAR-fusion at the step of filtering sequence-similar fusion pairs.
AKAP9 and BRAF share common sequences in certian regions  as below according to the all-vs-all BLAST+ results in 'trans.blast.align_coords.align_coords.dat' file.
AKAP9	[["92092656","92092939"],["92107561","92107869"]]	
BRAF	[["140731898","140732189"],["140780359","140780530"],["140780943","140781222"],["140799065","140799145"]] 
The break positions in my sample were out of the regions, but the AKAP9-BRAF fusion was filtered out.
It is good to filter out the fusion genes whose breaks occurred in the high-similarity regions, but the fusion gene shouldn't be removed if the breaks are not in the regions.
How can I include the AKAP9-BRAF fusion ?

**Comment by brianjohnhaas** [comment]
Hi

Yes, I noticed this recently.  Brought to my attention by Daniel
Nicoricci.  It turns out to be specific to the latest grch38 ctat genome
lib.  Works fine with hg19 and with older grch38 annotations.  I've got a
few other fixes going in to the next release.  Hopefully have it ready next
week.

-via googleFi

**Comment by brianjohnhaas** [comment]
This is resolved for the upcoming release.
