### ISSUE TITLE
use of pre computed pairwise blast data

### ISSUE THREAD

**Issue by htafer** [STAR-Fusion/STAR-Fusion#4]
Dear Brian

I am using STAR-Fusion on a newly sequenced genome. while the prediction step is fast, the filtering step needs around 24h to finish. This is due to the many blastn searches. By looking at the script/data inside the STAR-Fusion repository i saw that there is the possibility to use precomputed pairwise blastn tables like the one in resources/gencode.v19.annotation.gtf.exons.cdna.gz.blastn_gene_pairs.gz
I saw that there is a script  util/index_blast_pairs.pl that allows to index the gene_pair blastn file. This index is then automatically used by STAR-Fusion

I would like to generate the blastn_gene_pair file for my genome. How should i proceed?

**Comment by brianjohnhaas** [comment]
Hi,

All you need to do is to run blastn, capture the output as

     -outfmt 6

but the trickier part is that you need to ensure that the gene identifiers
end up in the first two columns of the output rather than the transcript
identifiers.  I had written a custom script to do this, but haven't
integrated the functionality into the toolkit nor documentation on this
yet.   Once you have the blast output in the proper format, you would run
the indexer.



On Thu, Jul 30, 2015 at 6:36 AM, htafer <notifications@github.com> wrote:

> Dear Brian
>
> I am using STAR-Fusion on a newly sequenced genome. while the prediction
> step is fast, the filtering step needs around 24h to finish. This is due to
> the many blastn searches. By looking at the script/data inside the
> STAR-Fusion repository i saw that there is the possibility to use
> precomputed pairwise blastn tables like the one in
> resources/gencode.v19.annotation.gtf.exons.cdna.gz.blastn_gene_pairs.gz
> I saw that there is a script util/index_blast_pairs.pl that allows to
> index the gene_pair blastn file. This index is then automatically used by
> STAR-Fusion
>
> I would like to generate the blastn_gene_pair file for my genome. How
> should i proceed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/4>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
